name: Build and Test JPF
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Build_and_Test_JPF:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3'
    - name: Update Gem
      run: gem update --system
    - name: install prereqs
      run: sudo apt install wget gnupg ca-certificates lsb-release python3 python3-pip python3-venv pipx ruby-full build-essential expect texlive-latex-base texlive-latex-extra tzdata libboost-date-time-dev libcppunit-dev zlib1g-dev
    - name: Install Jekyll
      run: gem install jekyll bundler --no-document
    - name: make
      run: make -C src
    - name: make check
      run: make -C src check

