name: Build and Test JPF
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Build_and_Test_JPF:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3'
    - name: Update Gem
      run: gem update --system
    - name: install prereqs
      run: sudo apt install build-essential libboost-date-time-dev libcppunit-dev zlib1g-dev pdflatex
    - name: Install Jekyll
      run: gem install jekyll bundler --no-document
    - name: make
      run: make -C src
    - name: make check
      run: make -C src check

