name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    - run: sudo apt install build-essential libboost-date-time-dev libcppunit-dev webfs podman

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: make check
      run: make check
