name: Make jpf
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  make_jpf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install prereqs
      run: sudo apt install build-essential libboost-date-time-dev libcppunit-dev
    - name: make
      run: make
    - name: make check
      run: make check
