name: Test the Deployed Debian Package

on:
  workflow_dispatch

jobs:
  Clean_Install_Using_Package:
    runs-on: ubuntu-20.04
    steps:
    - name: prepare to install jpf
      run: wget https://raw.githubusercontent.com/j842/jpf/main/install.sh && chmod a+x install.sh && sudo ./install.sh
    - name: install prereqs including jpf
      run: |
        sudo apt-get update
        sudo apt-get -y install jpf
    - name: test 1 - unit tests
      run: jpf -t
    - name: test 2 - install defaults
      run: |
        mkdir ~/test 
        jpf -c ~/test
        jpf ~/test
